# Spring Boot 환경설정하는 파일 (DB, Tomcat 등)

# Tomcat Server Port 변경
server.port=8081

# Context Path 수정
# Context Path를 수정하지 않으면 기본 Context Path는 → / 다 (localhost:8081/가 Contextd Path가 된다)
# Context Path를 → /boot 로 바꿀것이다 
server.servlet.context-path=/boot

# DB설정
#  드라이버위치잡기 
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/com
spring.datasource.username=com
spring.datasource.password=com01

# Spring JPA 설정 (JDBC → API) 이거를 → Hibernate(Spring JPA 구현체)가 한다 
# 레거시 Spring에서는 Mapper Interface에서는 추상메서드를 만들면 추상메서드를 구현하는 클래스는 
#  → SqlSessionFactoryBean 이 구현해서 만든다 하지만 SQL문장은 개발자가 짰다 
# Spring JPA 에서는 Hibernate : SQL Query를 빌드시킨다 (자동생성)
# 사용예시)
# JPA클래스.save(vo) 하면 알아서 메소드 이름 하나로 처리해준다  
#  → insert into Board(title, content, writer)
#    values (#{title}, #{content}, #{writer}) 
# 복잡한 쿼리는 직접 짜야하지만 간단한 SQL문은 작성을 알아서 해주는 장점이 있다  
# JPA/Hibernate를 방식을 → ORM(Object Relational Mapping, 객체관계매핑)방식 이라 한다 

# JPA 설정하기 
# JPA(Hibernate)한테 “우리 DB는 MySQL이야”라고 알려주는 설정
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect
# JPA가 실행될 때 DB 테이블을 자동으로 맞춰주는 설정, 스키마 생성(create, update)
spring.jpa.hibernate.ddl-auto=update
#JPA가 DB에 보내는 SQL을 콘솔에 보여주는 설정
spring.jpa.show-sql=true
#JPA가 DB에 보내는 SQL을 “보기 좋게 정렬해서” 보여주라는 설정
spring.jpa.properties.hibernate.format_sql=true

#Spring Boot ViewResolver 설정
spring.mvc.view.prefix=/WEB-INF/board/
spring.mvc.view.suffix=.jsp
















